// Generated by CoffeeScript 1.7.1
(function() {
  var StormTower, agent, argv, config, util;

  argv = require('optimist').usage('Start stormtower with a configuration file.\nUsage: $0 -c <config file>').demand('c')["default"]('c', '/etc/stormstack/stormtower.json').alias('c', 'file').describe('c', 'location of stormtower configuration file').argv;

  config = require('../package').config;

  GLOBAL.config = config;

  util = require('util');

  util.log("stormtower coming up as the NFV application controller...");

  StormTower = require('./stormtower');

  agent = new StormTower;

  agent.run();

}).call(this);
