// Generated by CoffeeScript 1.7.1
(function() {
  var stomp, stompConnect, url;

  stomp = require('stompjs');

  url = require('url');

  stompConnect = function(mqUrl, callback) {
    var connect, connectcb, creds, errorcb, purl;
    purl = url.parse(mqUrl);
    if (!purl) {
      return callback(new Error("Failed to parse URL " + mqUrl));
    }
    connectcb = (function(_this) {
      return function(frame) {
        return callback(client, purl.pathname);
      };
    })(this);
    errorcb = (function(_this) {
      return function(error) {
        console.log("stomp client failed due to error ", error);
        console.log("Reconnecting in 10 sec");
        return setTimeout(connect, 10000);
      };
    })(this);
    connect = (function(_this) {
      return function() {
        var client;
        client = stomp.overTCP(purl.host, purl.port);
        return client.connect(creds[0], creds[1], connectcb, errorcb);
      };
    })(this);
    creds = purl.auth.split(':');
    return connect();
  };

  module.exports = stompConnect;

}).call(this);
