// Generated by CoffeeScript 1.7.1
(function() {
  this.include = function() {
    var tower;
    tower = this.settings.agent;
    this.head({
      '/agents': function() {
        this.res.header('Content-MD5', tower.checksum());
        return this.res.send('');
      }
    });
    this.get({
      '/agents': function() {
        return this.send(tower.agents.list());
      }
    });
    return this.all({
      '/agents/:id/*': function() {
        var match;
        match = tower.agents.get(this.params.id);
        if ((match != null) && (match.bolt != null) && (match.bolt.relay != null)) {
          this.req.target = 8000;
          this.req.url = this.params[0];
          return match.bolt.relay(this.req, this.res);
        } else {
          return this.send(404);
        }
      }
    });
  };

}).call(this);
