// Generated by CoffeeScript 1.7.1
(function() {
  this.include = function() {
    var tower;
    tower = this.settings.agent;
    this.head({
      '/agents': function() {
        this.res.header('Content-MD5', tower.checksum());
        return this.res.send('');
      }
    });
    this.get({
      '/agents': function() {
        return this.send(tower.agents.list());
      }
    });
    return this.all({
      '/agents/:id/*': function() {
        var match, req;
        match = tower.agents.get(this.params.id);
        if ((match != null) && (match.bolt != null)) {
          req = request({
            method: this.req.method,
            uri: this.params[1],
            timeout: 5000,
            body: this.body
          });
          req.target = 8000;
          return match.bolt.relay(req, (function(_this) {
            return function(chunk, complete) {
              if (chunk instanceof Error) {
                _this.next(chunk);
              }
              if (complete) {
                return _this.send = chunk;
              }
            };
          })(this));
        } else {
          return this.send(404);
        }
      }
    });
  };

}).call(this);
