// Generated by CoffeeScript 1.7.1
(function() {
  var StormAgent, StormBolt, StormData, StormRegistry, StormTower, TowerAgent, TowerRegistry,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  StormAgent = require('stormagent');

  StormData = StormAgent.StormData;

  TowerAgent = (function(_super) {
    var async, crypto, http;

    __extends(TowerAgent, _super);

    async = require('async');

    http = require('http');

    crypto = require('crypto');

    function TowerAgent(id, bolt) {
      this.id = id;
      this.bolt = bolt;
      this.status = false;
      TowerAgent.__super__.constructor.call(this, id);
    }

    TowerAgent.prototype.monitor = function(interval, callback) {
      this.monitoring = true;
      return async.whilst((function(_this) {
        return function() {
          return _this.monitoring;
        };
      })(this), (function(_this) {
        return function(repeat) {
          var body, err, header, relay, req, streamBuffers;
          try {
            streamBuffers = require('stream-buffers');
            req = new streamBuffers.ReadableStreamBuffer;
            req.method = 'GET';
            req.url = '/';
            req.target = 5000;
            _this.log("monitor - checking " + _this.bolt.id);
            relay = _this.bolt.relay(req);
          } catch (_error) {
            err = _error;
            _this.log("agent discovery request failed:", err);
            setTimeout(repeat, interval);
          }
          header = null;
          body = '';
          relay.on('data', function(chunk) {
            try {
              if (!header) {
                return header = JSON.parse(chunk);
              } else {
                return body += chunk;
              }
            } catch (_error) {
              err = _error;
              _this.log("unable to parse header:", chunk);
              _this.log("error:", err);
              return relay.end();
            }
          });
          relay.on('end', function() {
            var checksum, md5, status;
            try {
              md5 = crypto.createHash("md5");
              md5.update(body);
              checksum = md5.digest("hex");
              if (checksum !== _this.checksum) {
                status = JSON.parse(body);
                return _this.status = status;
              }
            } catch (_error) {
              err = _error;
              _this.log("unable to parse body:", body);
              _this.log("error:", err);
              return relay.end();
            }
          });
          _this.log("scheduling repeat at " + interval);
          return setTimeout(repeat, interval);
        };
      })(this), (function(_this) {
        return function(err) {
          return _this.log("agent discovery stopped for: " + _this.id);
        };
      })(this));
    };

    TowerAgent.prototype.destroy = function() {
      return this.monitoring = false;
    };

    return TowerAgent;

  })(StormData);

  StormRegistry = StormAgent.StormRegistry;

  TowerRegistry = (function(_super) {
    __extends(TowerRegistry, _super);

    function TowerRegistry(filename) {
      this.on('removed', function(tagent) {
        if (tagent.destroy != null) {
          return tagent.destroy();
        }
      });
      TowerRegistry.__super__.constructor.call(this, filename);
    }

    TowerRegistry.prototype.get = function(key) {
      var entry, _base;
      entry = TowerRegistry.__super__.get.call(this, key);
      if (entry == null) {
        return;
      }
      if ((_base = entry.status).id == null) {
        _base.id = entry.id;
      }
      return entry.status;
    };

    return TowerRegistry;

  })(StormRegistry);

  StormBolt = require('stormbolt');

  StormTower = (function(_super) {
    var crypto;

    __extends(StormTower, _super);

    crypto = require("crypto");

    function StormTower(config) {
      StormTower.__super__.constructor.call(this, config);
      this["import"](module);
      this.agents = new TowerRegistry;
      this.checksum = function() {
        var agent, md5, _i, _len, _ref;
        md5 = crypto.createHash("md5");
        _ref = this.agents.list();
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          agent = _ref[_i];
          md5.update(agent);
        }
        return md5.digest("hex");
      };
      this.clients.on('added', (function(_this) {
        return function(bolt) {
          var entry;
          entry = _this.agents.add(bolt.id, new TowerAgent(bolt.id, bolt));
          entry.on('changed', function(status, checksum) {
            return this.agents.emit('changed');
          });
          return entry.monitor(_this.config.monitorInterval, function(status) {

            /*
            entry.status = data
            @agents.update bolt.id, entry
             */
          });
        };
      })(this));
      this.clients.on('removed', (function(_this) {
        return function(bolt) {
          return _this.agents.remove(bolt.id);
        };
      })(this));
    }

    StormTower.prototype.status = function() {
      var state;
      state = StormTower.__super__.status.apply(this, arguments);
      state.agents = this.agents.list();
      return state;
    };

    return StormTower;

  })(StormBolt);

  module.exports = StormTower;

}).call(this);
